"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import '../../../node_modules/bootstrap/dist/css/bootstrap.min.css';
import { useEffect, useState } from "react";

import Link from "next/link";
import NavbarMain from "./Components/NavbarMain";
import Footer from "./Components/Footer";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.bundle.min');
  }, []);


  const [solutionsOpen, setSolutionsOpen] = useState(false);
  const [servicesOpen, setServicesOpen] = useState(false);
  const [partnersOpen, setPartnersOpen] = useState(false);
  const [aboutOpen, setAboutOpen] = useState(false);

  const handleToggle = (menu) => {
    switch (menu) {
      case 'solutions':
        setSolutionsOpen(!solutionsOpen);
        break;
      case 'services':
        setServicesOpen(!servicesOpen);
        break;
      case 'partners':
        setPartnersOpen(!partnersOpen);
        break;
      case 'about':
        setAboutOpen(!aboutOpen);
        break;
      default:
        break;
    }
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarMain></NavbarMain>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
